package gui;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author audy
 */
public class MainFrame extends javax.swing.JFrame {
    private final DefaultTableModel model = new DefaultTableModel();
    private DbPelanggan koneksi = new DbPelanggan();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        model.addColumn("No Member");
        model.addColumn("Nama");
        model.addColumn("Tahun Lahir");
        model.addColumn("Jenis");

        TableMember.setModel(model);

        populateTable();
        ResetButton.setVisible(false);
        DeleteButton.setVisible(false);
    }
    
    private void populateTable() {
        model.setRowCount(0);
        try {
            ArrayList<Pelanggan> daftar = koneksi.getPelanggan();
            for (Pelanggan p : daftar) {
                Object[] isiData = {p.getId(), p.getNama(), p.getTahunLahir(), p.getKategori()};
                model.addRow(isiData);
            }
        } catch (SQLException ex) {
            System.out.println("Eksepsi: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
        }

    }
    
    private void populateTable(String keyword) {
        model.setRowCount(0);
        try {
            ArrayList<Pelanggan> daftar = koneksi.cariPelanggan(keyword);
            for (Pelanggan p : daftar) {
                Object[] isiData = {p.getId(), p.getNama(), p.getTahunLahir(), p.getKategori()};
                model.addRow(isiData);
            }
        } catch (SQLException ex) {
            System.out.println("Eksepsi: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
        }

    }
    
    private void kosongkan() {
        IdMemberField.setText("");
        NamaField.setText("");
        TahunLahirBox.setSelectedIndex(0);
        JenisMemberBox.setSelectedIndex(0);
        IdMemberField.setEditable(true);
        SaveButton.setText("Simpan");
        ResetButton.setVisible(false);
        DeleteButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        IdMemberLabel = new javax.swing.JLabel();
        IdMemberField = new javax.swing.JTextField();
        NamaLabel = new javax.swing.JLabel();
        NamaField = new javax.swing.JTextField();
        TahunLahirLabel = new javax.swing.JLabel();
        TahunLahirBox = new javax.swing.JComboBox<>();
        JenisMemberLabel = new javax.swing.JLabel();
        JenisMemberBox = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        CariField = new javax.swing.JTextField();
        CariButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMember = new javax.swing.JTable();
        DeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(218, 202, 205));
        setPreferredSize(new java.awt.Dimension(550, 650));

        jPanel1.setBackground(new java.awt.Color(218, 202, 205));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 600));
        jPanel1.setRequestFocusEnabled(false);

        judulLabel.setBackground(new java.awt.Color(85, 81, 104));
        judulLabel.setFont(new java.awt.Font("Pacifico", 0, 18)); // NOI18N
        judulLabel.setForeground(new java.awt.Color(85, 81, 104));
        judulLabel.setText("Formulir Daftar Pelanggan");

        IdMemberLabel.setBackground(new java.awt.Color(85, 81, 104));
        IdMemberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IdMemberLabel.setForeground(new java.awt.Color(85, 81, 104));
        IdMemberLabel.setText("ID Member:");

        IdMemberField.setBackground(new java.awt.Color(142, 173, 195));
        IdMemberField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdMemberField.setForeground(new java.awt.Color(69, 73, 74));

        NamaLabel.setBackground(new java.awt.Color(85, 81, 104));
        NamaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamaLabel.setForeground(new java.awt.Color(85, 81, 104));
        NamaLabel.setText("Nama:");

        NamaField.setBackground(new java.awt.Color(142, 173, 195));
        NamaField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NamaField.setForeground(new java.awt.Color(69, 73, 74));

        TahunLahirLabel.setBackground(new java.awt.Color(85, 81, 104));
        TahunLahirLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TahunLahirLabel.setForeground(new java.awt.Color(85, 81, 104));
        TahunLahirLabel.setText("Tahun Lahir: ");

        TahunLahirBox.setBackground(new java.awt.Color(142, 173, 195));
        TahunLahirBox.setForeground(new java.awt.Color(85, 81, 104));
        TahunLahirBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));

        JenisMemberLabel.setBackground(new java.awt.Color(85, 81, 104));
        JenisMemberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JenisMemberLabel.setForeground(new java.awt.Color(85, 81, 104));
        JenisMemberLabel.setText("Jenis Member:");

        JenisMemberBox.setBackground(new java.awt.Color(142, 173, 195));
        JenisMemberBox.setForeground(new java.awt.Color(85, 81, 104));
        JenisMemberBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silver", "Gold", "Platinum" }));

        SaveButton.setBackground(new java.awt.Color(0, 123, 255));
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("SIMPAN");
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveButtonMouseClicked(evt);
            }
        });

        ResetButton.setText("RESET");
        ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetButtonMouseClicked(evt);
            }
        });

        CariField.setBackground(new java.awt.Color(142, 173, 195));
        CariField.setForeground(new java.awt.Color(69, 73, 74));

        CariButton.setText("CARI");
        CariButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CariButtonMouseClicked(evt);
            }
        });

        TableMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Member", "Nama", "Tahun Lahir", "Jenis Member"
            }
        ));
        TableMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMember);

        DeleteButton.setText("Hapus");
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TahunLahirLabel)
                            .addComponent(NamaLabel)
                            .addComponent(IdMemberLabel)
                            .addComponent(JenisMemberLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaField)
                            .addComponent(IdMemberField)
                            .addComponent(TahunLahirBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(judulLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(JenisMemberBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(CariField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CariButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(judulLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdMemberLabel)
                    .addComponent(IdMemberField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaLabel)
                    .addComponent(NamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TahunLahirLabel)
                    .addComponent(TahunLahirBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JenisMemberLabel)
                    .addComponent(JenisMemberBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseClicked
        String nomor = IdMemberField.getText();
        String nama = NamaField.getText();
        String jenis = JenisMemberBox.getSelectedItem().toString();
        String tahunLahir = TahunLahirBox.getSelectedItem().toString();
        Pelanggan p = new Pelanggan(nomor, nama, jenis, Integer.parseInt(tahunLahir));

        if (SaveButton.getText().equals("Simpan")) {
            try {
                if (koneksi.insertPelanggan(p)) {
                    JOptionPane.showMessageDialog(this, "Berhasil Insert");
                    populateTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal Insert");
                }
            } catch (SQLException ex) {
                System.out.println("Eksepsi: " + ex.getMessage());
                JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
            }
        } else {
            try {
                int jawaban = JOptionPane.showConfirmDialog(this, "Ubah Data " + p.getId() + "?", "Ubah", JOptionPane.YES_NO_OPTION);
                if (jawaban == JOptionPane.YES_OPTION) {
                    if (koneksi.updatePelanggan(p)) {
                        JOptionPane.showMessageDialog(this, "Berhasil Update");
                        populateTable();
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal Update");
                    }
                }
            } catch (SQLException ex) {
                System.out.println("Eksepsi: " + ex.getMessage());
                JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
            }
        }
        kosongkan();
    }//GEN-LAST:event_SaveButtonMouseClicked

    private void ResetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseClicked
        kosongkan();
    }//GEN-LAST:event_ResetButtonMouseClicked

    private void CariButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CariButtonMouseClicked
        String keyword = CariField.getText();
        populateTable(keyword);
    }//GEN-LAST:event_CariButtonMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        int selectedRow = TableMember.getSelectedRow();
        String id = model.getValueAt(selectedRow, 0).toString();
        int jawaban = JOptionPane.showConfirmDialog(this, "Hapus Data " + id + "?", "Hapus", JOptionPane.YES_NO_OPTION);
        if (jawaban == JOptionPane.YES_OPTION) {
            try {
                if (koneksi.deletePelanggan(id)) {
                    JOptionPane.showMessageDialog(this, "Berhasil Delete");
                    populateTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal Delete");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Eksepsi: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void TableMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMemberMouseClicked
        int selectedRow = TableMember.getSelectedRow();
        String id = model.getValueAt(selectedRow, 0).toString();
        String nama = model.getValueAt(selectedRow, 1).toString();
        String tahun = model.getValueAt(selectedRow, 2).toString();
        String jenis = model.getValueAt(selectedRow, 3).toString();

        IdMemberField.setText(id);
        IdMemberField.setEditable(false);
        NamaField.setText(nama);
        JenisMemberBox.setSelectedItem(jenis);
        TahunLahirBox.setSelectedItem(tahun);
        SaveButton.setText("Ubah");
        ResetButton.setVisible(true);
        DeleteButton.setVisible(true);
    }//GEN-LAST:event_TableMemberMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CariButton;
    private javax.swing.JTextField CariField;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField IdMemberField;
    private javax.swing.JLabel IdMemberLabel;
    private javax.swing.JComboBox<String> JenisMemberBox;
    private javax.swing.JLabel JenisMemberLabel;
    private javax.swing.JTextField NamaField;
    private javax.swing.JLabel NamaLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTable TableMember;
    private javax.swing.JComboBox<String> TahunLahirBox;
    private javax.swing.JLabel TahunLahirLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulLabel;
    // End of variables declaration//GEN-END:variables
}
